WAVEngine(Homework4): changeSpeed.h File Reference
changeSpeed.h File Reference
This program is for speed change option. You can choose a number between (0, 100000) (0 and 100000 are not included) and then you choose the wave files you want to change the speed. The speed of the changed music files will be x times faster than the original, where x is the number you chose. Note that x can be lower than 1, so if you choose a number between 0 and 1 (0,1) the new file(s) will have lower speed. For example if you choose to change speed 0.5, the new file(s) will be 2 times slower. e.g. ./wavengine -changeSpeed 2 piano.wav Results: if piano.wav is in the same folder as wavengine, a new file will be created named "5-times-speed-changed-piano.wav" which is piano.wav 5 times faster.
#include "header.h"
#include "iolib.h"
Functions
int speedChange (char const *fileName, char *speedChange)
Detailed Description
This program is for speed change option. You can choose a number between (0, 100000) (0 and 100000 are not included) and then you choose the wave files you want to change the speed. The speed of the changed music files will be x times faster than the original, where x is the number you chose. Note that x can be lower than 1, so if you choose a number between 0 and 1 (0,1) the new file(s) will have lower speed. For example if you choose to change speed 0.5, the new file(s) will be 2 times slower. e.g. ./wavengine -changeSpeed 2 piano.wav Results: if piano.wav is in the same folder as wavengine, a new file will be created named "5-times-speed-changed-piano.wav" which is piano.wav 5 times faster.
Author
Christoforos Seas (cseas.nosp@m.002@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-12-04
Copyright
Copyright (c) 2021 Christoforos Seas. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
speedChange()
int speedChange (char const * fileName, char * speedChange)
 {
     float speedChangeNum = atof(speedChange);
     if (speedChangeNum <= 0)
     {
         printf("The speed must be a value greater than 0\n");
         return EXIT_FAILURE;
     }
     if (speedChangeNum >= 100000)
     {
         printf("The speed must be a value lower than 100000\n");
         return EXIT_FAILURE;
     }
     char *timesChanged = (char *)malloc((strlen(speedChange) + 22) * sizeof(char));
     // <strlen(speedChange)>-times-speed-changed-\0 is 22 characters + strlen(speedChange)
     strcpy(timesChanged, speedChange);
     strcat(timesChanged, "-times-speed-changed-");
     char *newFileName = (char *)malloc(strlen(fileName) + 1 + strlen(timesChanged));
     MUSIC_FILE *musicFile = NULL;
     if (!(musicFile = (MUSIC_FILE *)malloc(sizeof(MUSIC_FILE))))
         return EXIT_FAILURE;
     if (readHeaderAndData(musicFile, fileName) == EXIT_FAILURE)
     {
         printf("Failed to read music file\n");
         return EXIT_FAILURE;
     }
     musicFile->fmtSub->sampleRate *= speedChangeNum; // changing speed
     if (changedName(newFileName, fileName, timesChanged) == EXIT_FAILURE)
         return EXIT_FAILURE;
     if (writeFile(musicFile, newFileName) == EXIT_FAILURE)
         return EXIT_FAILURE;
     free(newFileName);
     free(timesChanged);
     freeMusicFile(musicFile);
     return EXIT_SUCCESS;
 }
References changedName(), MUSIC_FILE::fmtSub, freeMusicFile(), readHeaderAndData(), FMT_SUB::sampleRate, and writeFile().
Referenced by wavengine().