WAVEngine(Homework4): chop.h File Reference
chop.h File Reference
This program is used to chop a music file to a smaller one. The customer chooses the starting and ending second, and a new file named chopped-<old music file name> will be created. This new file will be the music file given chopped from starting second to ending second (which the customer chooses).
#include "iolib.h"
#include "header.h"
#include <stdbool.h>
Functions
bool secondsAreValid (MUSIC_FILE *, int startSecond, int endSecond)
secondsAreValid is a function which checks whether the input seconds are valid.
int createChoppedFile (MUSIC_FILE *choppedMusicFile, int startSecond, int endSecond, char const *fileName)
Create a Chopped File object from the given start second to the given end second and then save the output to a new file.
int chop (char const *fileName, int startSecond, int endSecond)
The main function which reads the input file and chops the file from start second to end second and then saves the output to a new file.
Detailed Description
This program is used to chop a music file to a smaller one. The customer chooses the starting and ending second, and a new file named chopped-<old music file name> will be created. This new file will be the music file given chopped from starting second to ending second (which the customer chooses).
Author
Christoforos Seas (cseas.nosp@m.002@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-12-04
Copyright
Copyright (c) 2021 Christoforos Seas, Lampros Dionysiou. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
chop()
int chop (char const * fileName, int startSecond, int endSecond)
The main function which reads the input file and chops the file from start second to end second and then saves the output to a new file.
Parameters
fileName the file name
startSecond the start second
endSecond the end second
Returns
int EXIT_SUCCESS or EXIT_FAILURE, whether the program ends successfully or not
{
     char* newFileName = NULL;
     newFileName = (char*) malloc(strlen(fileName) + 9 * sizeof(char));
     //chopped-\0 is 8 characters
     if (!newFileName) {
         printf("Cannot allocate space for new file name\n");
         return EXIT_FAILURE;
     }
     MUSIC_FILE* choppedMusicFile = NULL;
     if (!(choppedMusicFile = (MUSIC_FILE*) malloc(sizeof(MUSIC_FILE)))) {
         free(newFileName);
         return EXIT_FAILURE;
     }
     if (changedName(newFileName, fileName, "chopped-") == EXIT_FAILURE) {
         free(newFileName);
         free(choppedMusicFile);
         return EXIT_FAILURE;
     }
     if (readHeaderAndData(choppedMusicFile, fileName) == EXIT_FAILURE) {
         printf("Failed to read music file\n");
         free(newFileName);
         free(choppedMusicFile);
         return EXIT_FAILURE;
     }
     if (!secondsAreValid(choppedMusicFile, startSecond, endSecond)) {
         free(newFileName);
         free(choppedMusicFile);
         return EXIT_FAILURE;
     }
     if (createChoppedFile(choppedMusicFile, startSecond, endSecond, newFileName) == EXIT_FAILURE) {
         free(newFileName);
         free(choppedMusicFile);
         return EXIT_FAILURE;
     }
     free(newFileName);
     freeMusicFile(choppedMusicFile);
     return EXIT_SUCCESS;
 }
References changedName(), createChoppedFile(), freeMusicFile(), readHeaderAndData(), and secondsAreValid().
Referenced by wavengine().
createChoppedFile()
int createChoppedFile (MUSIC_FILE * choppedMusicFile, int startSecond, int endSecond, char const * fileName)
Create a Chopped File object from the given start second to the given end second and then save the output to a new file.
Parameters
choppedMusicFile the chopped music file
startSecond the start second
endSecond the end second
fileName the filename where the music file is. (.wav file)
Returns
int EXIT_SUCCESS or EXIT_FAILURE, whether the program ends successfully or not
{
     int byteRate = choppedMusicFile -> fmtSub -> byteRate;
     dword newSize = (endSecond - startSecond) * byteRate;
     choppedMusicFile -> size = newSize;
     choppedMusicFile -> dataSub -> subChunk2Size = newSize;
     choppedMusicFile -> riff -> chunkSize = newSize + 36;
     // chunk size is the new data size + 36 (header fields - 8) (36 in hex is)
     byte* newData = NULL;
     if (!(newData = (byte*) malloc(newSize))) {
         printf("Cannot allocate memory for new data\n");
         return EXIT_FAILURE;
     }
     int i, startLength = startSecond * byteRate + 44, endLength = endSecond * byteRate + 44;
     // we add 44 because that's the header byte size (all chunks size)
     for (i = startLength; i < endLength; i++)
         *(newData + i - startLength) = *(choppedMusicFile -> data + i);
     free(choppedMusicFile -> data);
     choppedMusicFile -> data = newData;
     writeFile(choppedMusicFile, newFileName);
     return EXIT_SUCCESS;
 }
References writeFile().
Referenced by chop().
secondsAreValid()
bool secondsAreValid (MUSIC_FILE * , int startSecond, int endSecond)
secondsAreValid is a function which checks whether the input seconds are valid.
Valid seconds are those within the boundaries of the music file. e.g. if a wave file is 10 seconds long, the end second must be an integer from 1 to 10, and the start second must be an integer from 0 to 9. Note that start second cannot be greater or equal to the end second and it must be a positive number.
Parameters
startSecond the start second
endSecond the end second
Returns
true if the seconds are valid
false otherwise
{
     // the total time of a wave music file can be calculated using this formula:
     // time = FileLength / ByteRate
     if (startSecond >= endSecond) {
         printf("The starting second cannot be greater or equal to the end second\n");
         return false;
     }
     if (startSecond < 0) {
         printf("The starting second cannot be a negative number\n");
         return false;
     }
     if (endSecond > musicFile -> size / musicFile -> fmtSub -> byteRate) {
         printf("The file is shorter than %d seconds\n", endSecond);
         return false;
     }
     return true;
 }
Referenced by chop().