WAVEngine(Homework4): cryptography.h File Reference
cryptography.h File Reference
This program provides some basic functions needed for the encryption and decryption of data.
#include "header.h"
#include "iolib.h"
Functions
int * createPermutationFunction (int N, unsigned int systemkey)
Creates a Permutation Function array with random indices from 0 to N-1.
void swap (int *num1, int *num2)
Swaps two cells in an array.
Detailed Description
This program provides some basic functions needed for the encryption and decryption of data.
Author
Christoforos Seas (cseas.nosp@m.002@.nosp@m.ucy.a.nosp@m.c.cy)
Lampros Dionysiou (ldion.nosp@m.y01@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-12-04
Copyright
Copyright (c) 2021 Christoforos Seas, Lampros Dionysiou. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
createPermutationFunction()
int* createPermutationFunction (int N, unsigned int systemkey)
Creates a Permutation Function array with random indices from 0 to N-1.
Parameters
N The number of audio samples
systemkey An encryption key.
Returns
An array with random indices.
 {
     int i;
     int *permutation = (int *) malloc((N * sizeof(int)));
     srand(systemkey);
     for (i = 0; i < N; i++)
         *(permutation + i) = i;
     for (i = 0; i < N; i++)
     {
         int rand1 = rand() % N;
         int rand2 = rand() % N;
         swap(permutation + rand1, permutation + rand2);
     }
     return permutation;
 }
References swap().
Referenced by decryption(), and encryption().
swap()
void swap (int * num1, int * num2)
Swaps two cells in an array.
Parameters
num1 The address of the first cell.
num2 The address of the second cell.
 {
     int temp = *num1;
     *num1 = *num2;
     *num2 = temp;
 }
Referenced by createPermutationFunction().