WAVEngine(Homework4): encryption.h File Reference
encryption.h File Reference
This program encrypts a message into the audio file. It reads the audio file provided and stores in random samples a bit of the message. It then saves the output audio file using the name encoded-<input filename>.wav.
#include "cryptography.h"
Functions
int encryption (const char *fileName, const char *text)
Method that encrypts a message into an audio file.
Detailed Description
This program encrypts a message into the audio file. It reads the audio file provided and stores in random samples a bit of the message. It then saves the output audio file using the name encoded-<input filename>.wav.
Author
Christoforos Seas (cseas.nosp@m.002@.nosp@m.ucy.a.nosp@m.c.cy)
Lampros Dionysiou (ldion.nosp@m.y01@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-12-04
Copyright
Copyright (c) 2021 Christoforos Seas, Lampros Dionysiou. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
encryption()
int encryption (const char * fileName, const char * text)
Method that encrypts a message into an audio file.
It reads the header and data from an audio file using the filename provided. Using the rand function it chooses the samples to store the message. It takes each bit of the message and stores it in the last significant bit of random samples. It then exports the new audio file with the name encoded-<input filename>.wav. The audio file sounds the same after encryption.
Parameters
fileName The name of the file to be read.
text The message to be encrypted inside the wav file.
Returns
An exit code.
 {
     MUSIC_FILE *musicFile = NULL;
     if (!(musicFile = (MUSIC_FILE *)malloc(sizeof(MUSIC_FILE))))
         return EXIT_FAILURE;
     if (readHeaderAndData(musicFile, fileName) == EXIT_FAILURE)
     {
         printf("Failed to read music file\n");
         return EXIT_FAILURE;
     }
     FILE *fp = fopen(text, "r");
     if (!fp)
     {
         printf("Failed to read input file\n");
         freeMusicFile(musicFile);
         return EXIT_FAILURE;
     }
     fseek(fp, 0, SEEK_END);
     int fileSize = ftell(fp);
     fseek(fp, 0, SEEK_SET);
     char *word = (char *)malloc((fileSize + 1) * sizeof(char));
     if(!word)
     {
         printf("Failed to allocate memory\n");
         freeMusicFile(musicFile);
         return EXIT_FAILURE;
     }
     // + 1 for '\0'
     if (fread(word, sizeof(char), fileSize, fp) != fileSize)
     {
         printf("Failed to read input file\n");
         freeMusicFile(musicFile);
         free(word);
         return EXIT_FAILURE;
     }
     if (musicFile->size < strlen(word) * 8)
     {
         printf("Wave file size too low to encrypt the given word\n");
         free(word);
         freeMusicFile(musicFile);
         fclose(fp);
         return EXIT_FAILURE;
     }
     int *permutation = createPermutationFunction(musicFile->size, SYSTEM_KEY_INTEGER);
     if(!permutation){
         printf("Failed to initialize permutation array\n");
         free(word);
         freeMusicFile(musicFile);
         fclose(fp);
         return EXIT_FAILURE;
     }
     insertBits(permutation, word, musicFile);
     free(word);
     free(permutation);
     char *newFileName = (char *)malloc((strlen(fileName) + 9) * sizeof(char));
     // "encoded-\0" is 9 bytes
     if(!newFileName)
     {
         printf("Error while creating the output file\n");
         fclose(fp);
         freeMusicFile(musicFile);
         return EXIT_FAILURE;
     }
     if(changedName(newFileName, fileName, "encoded-") == EXIT_FAILURE)
     {
         printf("Error while creating the output file\n");
         fclose(fp);
         free(newFileName);
         freeMusicFile(musicFile);
         return EXIT_FAILURE;
     }
     fclose(fp);
     if(writeFile(musicFile, newFileName) == EXIT_FAILURE)
     {
         printf("Error while saving the output file\n");
         free(newFileName);
         freeMusicFile(musicFile);
         return EXIT_FAILURE;
     }
     free(newFileName);
     freeMusicFile(musicFile);
     return EXIT_SUCCESS;
 }
References changedName(), createPermutationFunction(), freeMusicFile(), insertBits(), readHeaderAndData(), MUSIC_FILE::size, SYSTEM_KEY_INTEGER, and writeFile().
Referenced by wavengine().