WAVEngine(Homework4): mix.c File Reference
mix.c File Reference
The implemenation of mix.h file.
#include "mix.h"
Functions
int changeMixedData (MUSIC_FILE *newFile, MUSIC_FILE *file1, MUSIC_FILE *file2)
int saveMixedFiles (MUSIC_FILE *newFile, char const *filename1, char const *filename2)
int mix (char const *filename1, char const *filename2)
This method merges two audio files into one.
Detailed Description
The implemenation of mix.h file.
Author
Lampros Dionysiou (ldion.nosp@m.y01@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-12-04
Copyright
Copyright (c) 2021 Lampros Dionysiou. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
changeMixedData()
int changeMixedData (MUSIC_FILE * newFile, MUSIC_FILE * file1, MUSIC_FILE * file2)
 {
     if (newFile->fmtSub->bitsPerSample == 8)
         for (int i = 0, j = 0; i < newFile->size; j += 2, i += 2)
         {
             newFile->data[i] = file1->data[j];
             newFile->data[i + 1] = file2->data[j + 1];
         }
     else if (newFile->fmtSub->bitsPerSample == 16)
         for (int i = 0, j = 0; i < newFile->size; j += 4, i += 4)
         {
             newFile->data[i] = file1->data[j];
             newFile->data[i + 1] = file1->data[j + 1];
             newFile->data[i + 2] = file2->data[j + 2];
             newFile->data[i + 3] = file2->data[j + 3];
         }
     else
         return EXIT_FAILURE;
     return EXIT_SUCCESS;
 }
References FMT_SUB::bitsPerSample, MUSIC_FILE::data, MUSIC_FILE::fmtSub, and MUSIC_FILE::size.
Referenced by mix().
mix()
int mix (char const * filename1, char const * filename2)
This method merges two audio files into one.
It reads the header and data from both files. It creates a new audio file using the left channel of the first file and the right channel of the second one. The size of the new audio file is the size of the smaller file. If the two files do not have the same number of bits per sample or either of those is mono, then the function terminates.
Parameters
filename1 The name of the first file (left channel).
filename2 The name of the second file (right channel).
Returns
An exit code.
 {
     if (!filename1 || !filename2)
         return EXIT_FAILURE;
     MUSIC_FILE *file1 = (MUSIC_FILE *)malloc(sizeof(MUSIC_FILE));
     MUSIC_FILE *file2 = (MUSIC_FILE *)malloc(sizeof(MUSIC_FILE));
     if(!file1 || !file2 || readHeaderAndData(file1, filename1) == EXIT_FAILURE || readHeaderAndData(file2, filename2) == EXIT_FAILURE){
         freeMusicFile(file1);
         freeMusicFile(file2);
         return EXIT_FAILURE;
     }
     if (file1->fmtSub->numChannels == 1 || file2->fmtSub->numChannels == 1 || file1->fmtSub->bitsPerSample != file2->fmtSub->bitsPerSample){
         freeMusicFile(file1);
         freeMusicFile(file2);
         return EXIT_FAILURE;
     }
     //Create new music file
     MUSIC_FILE *newFile = (MUSIC_FILE *)malloc(sizeof(MUSIC_FILE));
     if (!newFile){
         freeMusicFile(file1);
         freeMusicFile(file2);
         return EXIT_FAILURE;
     }
     //Change Header
     if(file1->size < file2->size){
         if(copyHeader(file1, newFile) == EXIT_FAILURE){
             freeMusicFile(file1);
             freeMusicFile(file2);
             freeMusicFile(newFile);
             return EXIT_FAILURE;
         }
     }
     else{
         if(copyHeader(file2, newFile) == EXIT_FAILURE){
             freeMusicFile(file1);
             freeMusicFile(file2);
             freeMusicFile(newFile);
             return EXIT_FAILURE;
         }
     }
     //Change Data
     newFile->data = (byte *)malloc(newFile->size);
     if (!newFile->data || changeMixedData(newFile, file1, file2) == EXIT_FAILURE){
         freeMusicFile(file1);
         freeMusicFile(file2);
         freeMusicFile(newFile);
         return EXIT_FAILURE;
     }
     //Save to file
     if(saveMixedFiles(newFile, filename1, filename2) == EXIT_FAILURE){
         freeMusicFile(file1);
         freeMusicFile(file2);
         freeMusicFile(newFile);
         return EXIT_FAILURE;
     }
     freeMusicFile(file1);
     freeMusicFile(file2);
     freeMusicFile(newFile);
     return EXIT_SUCCESS;
 }
References FMT_SUB::bitsPerSample, changeMixedData(), copyHeader(), MUSIC_FILE::data, MUSIC_FILE::fmtSub, freeMusicFile(), FMT_SUB::numChannels, readHeaderAndData(), saveMixedFiles(), and MUSIC_FILE::size.
Referenced by wavengine().
saveMixedFiles()
int saveMixedFiles (MUSIC_FILE * newFile, char const * filename1, char const * filename2)
 {
     if(!newFile || !filename1 || !filename2)
         return EXIT_FAILURE;
     char *newFilename = (char *)malloc(strlen(filename1) + strlen(filename2) + 5);
     // mix-<strlen(filename1)>-<strlen(filename2)>
     if (!newFilename)
         return EXIT_FAILURE;
     if(changedName(newFilename, filename1, "mix-") == EXIT_FAILURE){
         free(newFilename);
         return EXIT_FAILURE;
     }
     newFilename[strlen(newFilename) - 4] = '\0';
     // deleting ".wav" extention
     if(!strcat(newFilename, "-")){ // adds '-'
         free(newFilename);
         return EXIT_FAILURE;
     }
     char *tempFilename2 = (char *)filename2;
     if(changedName(tempFilename2, filename2, "") == EXIT_FAILURE){ // removing slashes
         free(newFilename);
         return EXIT_FAILURE;
     }
     if(!strcat(newFilename, tempFilename2)){
         free(newFilename);
         return EXIT_FAILURE;
     }
     if(writeFile(newFile, newFilename) == EXIT_FAILURE){
         free(newFilename);
         return EXIT_FAILURE;
     }
     free(newFilename);
     return EXIT_SUCCESS;
 }
References changedName(), and writeFile().
Referenced by mix().