WAVEngine(Homework4): readMusicFile.c File Reference
readMusicFile.c File Reference
The implementation of readMusicFile.h file.
#include "readMusicFile.h"
Functions
int copyHeader (MUSIC_FILE *musicFile, MUSIC_FILE *newFile)
int readHeaderAndData (MUSIC_FILE *musicFile, char const *fileName)
Method that reads the header and data of a binary wav file and saves them in a MUSIC_FILE struct.
Detailed Description
The implementation of readMusicFile.h file.
Author
Christoforos Seas (cseas.nosp@m.002@.nosp@m.ucy.a.nosp@m.c.cy)
Lampros Dionysiou (ldion.nosp@m.y01@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-12-04
Copyright
Copyright (c) 2021 Christoforos Seas, Lampros Dionysiou. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
copyHeader()
int copyHeader (MUSIC_FILE * musicFile, MUSIC_FILE * newFile)
{
     if (!((newFile -> riff = (RIFF*) malloc(sizeof(RIFF))) &&
      (newFile -> fmtSub = (FMT_SUB*) malloc(sizeof(FMT_SUB))) &&
      (newFile -> dataSub = (DATA_SUB*) malloc(sizeof(DATA_SUB))))) {
         printf("Cannot allocate space for reverse file\n");
         return EXIT_FAILURE;
     }
     *newFile->riff = *musicFile->riff;
     *newFile->fmtSub = *musicFile->fmtSub;
     *newFile->dataSub = *musicFile->dataSub;
     newFile->size = musicFile->size;
     return EXIT_SUCCESS;
 }
References MUSIC_FILE::dataSub, MUSIC_FILE::fmtSub, MUSIC_FILE::riff, and MUSIC_FILE::size.
Referenced by mix(), reverse(), and stereoToMono().
readHeaderAndData()
int readHeaderAndData (MUSIC_FILE * , char const * fileName)
Method that reads the header and data of a binary wav file and saves them in a MUSIC_FILE struct.
It allocates the necessary space for the struct.
Parameters
fileName The name of the file to be read.
Returns
An exit code.
{
     FILE* fp = NULL;
     if (!(fp = fopen(fileName, "rb"))) return EXIT_FAILURE;
     if (!(musicFile -> riff = (RIFF*) malloc(sizeof(RIFF)))) {
         fclose(fp);
         return EXIT_FAILURE;
     }
     if(fread(musicFile -> riff, sizeof(RIFF), 1, fp)!=1){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if (!(musicFile -> fmtSub = (FMT_SUB*) malloc(sizeof(FMT_SUB)))){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if(fread(musicFile -> fmtSub, sizeof(FMT_SUB), 1, fp)!=1){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if (!(musicFile -> dataSub = (DATA_SUB*) malloc(sizeof(DATA_SUB)))){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if(fread(musicFile -> dataSub, sizeof(DATA_SUB), 1, fp)!=1){
         fclose(fp);
         return EXIT_FAILURE;
     }
     musicFile -> size = musicFile -> dataSub -> subChunk2Size;
     if (!(musicFile -> data = (byte*) malloc(musicFile -> size))){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if(fread(musicFile -> data, sizeof(byte), musicFile -> size, fp)!=musicFile->size){
         fclose(fp);
         return EXIT_FAILURE;
     }
     fclose(fp);
     return EXIT_SUCCESS;
 }
References MUSIC_FILE::size.
Referenced by changeVol(), chop(), decryption(), encryption(), mix(), printList(), reverse(), speedChange(), and stereoToMono().