WAVEngine(Homework4): stereoToMono.h File Reference
stereoToMono.h File Reference
Stereo To Mono Converter. This program reads a binary wav music file and converts its audio to mono. The output music file is named mono-<input file name>.wav.
#include "header.h"
#include "iolib.h"
Functions
int stereoToMono (char const *fileName)
Method that converts an audio file from stero to mono.
Detailed Description
Stereo To Mono Converter. This program reads a binary wav music file and converts its audio to mono. The output music file is named mono-<input file name>.wav.
Author
Lampros Dionysiou (ldion.nosp@m.y01@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-12-04
Copyright
Copyright (c) 2021 Lampros Dionysiou. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
stereoToMono()
int stereoToMono (char const * fileName)
Method that converts an audio file from stero to mono.
It reads an audio file using the given filename and creates a new output wav file using the left audio channel. The name of the output file is mono-<input filename>.wav.
Parameters
fileName The filename of the input file
Returns
An exit code
{
     MUSIC_FILE* musicFile = (MUSIC_FILE*) malloc(sizeof(MUSIC_FILE));
     if(!musicFile || !fileName) return EXIT_FAILURE;
     if (readHeaderAndData(musicFile, fileName) == EXIT_FAILURE) return EXIT_FAILURE;
     if(musicFile->fmtSub->numChannels ==1 ){
         printf("WAV File is already Mono.");
         return EXIT_FAILURE;
     }
     MUSIC_FILE *newFile = (MUSIC_FILE*) malloc(sizeof(MUSIC_FILE));
     if (!newFile){
         freeMusicFile(musicFile);
         return EXIT_FAILURE;
     }
     //Header
     if(copyHeader(musicFile, newFile) || changeHeader(newFile)) {
         freeMusicFile(musicFile);
         freeMusicFile(newFile);
         return EXIT_FAILURE;
     }
     //Data
     newFile->data = (byte*) malloc(newFile->size);
     if(!newFile->data || changeData(musicFile, newFile)){
         freeMusicFile(musicFile);
         freeMusicFile(newFile);
         return EXIT_FAILURE;
     }
     //Save to file
     if(saveToFile(newFile, fileName)){
         freeMusicFile(musicFile);
         freeMusicFile(newFile);
         return EXIT_FAILURE;
     }
     freeMusicFile(newFile);
     freeMusicFile(musicFile);
     return EXIT_SUCCESS;
 }
References changeData(), changeHeader(), copyHeader(), MUSIC_FILE::data, MUSIC_FILE::fmtSub, freeMusicFile(), FMT_SUB::numChannels, readHeaderAndData(), saveToFile(), and MUSIC_FILE::size.
Referenced by wavengine().