WAVEngine(Homework4): writeMusicFile.h File Reference
writeMusicFile.h File Reference
This interface provides the necessary functions to create an output file and export the audio header and data.
#include "header.h"
Functions
int changedName (char *newFileName, char const *fileName, char *addition)
Method that removes any prefixes from the given filename and adds the given prefix (indicating the epl232_team9 library function).
int writeFile (MUSIC_FILE *musicFile, char const *newFileName)
Method that creates a new file using the given filename and exports the audio file in binary form.
void freeMusicFile (MUSIC_FILE *musicFile)
Method that frees the memory allocated for the music file's header and data.
Detailed Description
This interface provides the necessary functions to create an output file and export the audio header and data.
Author
Christoforos Seas (cseas.nosp@m.002@.nosp@m.ucy.a.nosp@m.c.cy)
Lampros Dionysiou (ldion.nosp@m.y01@.nosp@m.ucy.a.nosp@m.c.cy)
Version
0.1
Date
2021-11-25
Copyright
Copyright (c) 2021 Christoforos Seas, Lampros Dionysiou. This file is part of WAV Engine. WAV Engine is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Υou should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
changedName()
int changedName (char * newFileName, char const * fileName, char * addition)
Method that removes any prefixes from the given filename and adds the given prefix (indicating the epl232_team9 library function).
For example if the given filename is ./folder1/folder2/audio.wav and the prefix is 'mono', the new filename will be mono-audio.wav. This method DOES NOT allocate memory for the new filename. The caller of this method should allocate enough memory.
Parameters
newFileName The new filename after change.
fileName The filename to by changed.
addition The new prefix
Returns
An exit code.
 { // addition = "-mono", "-chop", etc.
     char *changedFilename = (char *)malloc(strlen(fileName) + 1);
     char *temp = changedFilename;
     if (strrchr(fileName, '/'))
     {
         changedFilename = strrchr(fileName, '/');
         if (changedFilename[0] == '/')
             changedFilename++;
     }
     else
         strcpy(changedFilename, fileName);
     if (!newFileName){
         free(temp);
         return EXIT_FAILURE;
     }
     if (!strcpy(newFileName, addition)){
         free(temp);
         return EXIT_FAILURE;
     }
     if (!strcat(newFileName, changedFilename)){
         free(temp);
         return EXIT_FAILURE;
     }
     free(temp);
     return EXIT_SUCCESS;
 }
Referenced by changeVol(), chop(), encryption(), reverse(), saveMixedFiles(), saveToFile(), and speedChange().
freeMusicFile()
void freeMusicFile (MUSIC_FILE * musicFile)
Method that frees the memory allocated for the music file's header and data.
Parameters
musicFile The header and data of the audio file.
 {
     if(!musicFile) return;
     if(!musicFile->riff) free(musicFile->riff);
     if(!musicFile->fmtSub) free(musicFile->fmtSub);
     if(!musicFile->dataSub)free(musicFile->dataSub);
     if(!musicFile->data)free(musicFile->data);
     free(musicFile);
 }
References MUSIC_FILE::data, MUSIC_FILE::dataSub, MUSIC_FILE::fmtSub, and MUSIC_FILE::riff.
Referenced by changeVol(), chop(), decryption(), encryption(), mix(), printList(), reverse(), speedChange(), and stereoToMono().
writeFile()
int writeFile (MUSIC_FILE * musicFile, char const * newFileName)
Method that creates a new file using the given filename and exports the audio file in binary form.
If the file already exists, it will be overwritten.
Parameters
musicFile The header and data of the audio file to be written.
newFileName The filename of the output file to be created.
Returns
An exit code.
 {
     FILE *fp = NULL;
     if (!(fp = fopen(newFileName, "wb")))
     {
         printf("Cannot create new file\n");
         return EXIT_FAILURE;
     }
     if(fwrite(musicFile->riff, sizeof(RIFF), 1, fp)!=1){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if(fwrite(musicFile->fmtSub, sizeof(FMT_SUB), 1, fp)!=1){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if(fwrite(musicFile->dataSub, sizeof(DATA_SUB), 1, fp)!=1){
         fclose(fp);
         return EXIT_FAILURE;
     }
     if(fwrite(musicFile->data, sizeof(byte), musicFile->size, fp)!=musicFile->size){
         fclose(fp);
         return EXIT_FAILURE;
     }
     fclose(fp);
     return EXIT_SUCCESS;
 }
References MUSIC_FILE::data, MUSIC_FILE::dataSub, MUSIC_FILE::fmtSub, MUSIC_FILE::riff, and MUSIC_FILE::size.
Referenced by changeVol(), createChoppedFile(), encryption(), reverse(), saveMixedFiles(), saveToFile(), and speedChange().